show databases;
use projects;
show tables;
select * from mytable;

-- revenue generated by demoragphics

select gender, sum(purchase_amount) from mytable group by gender;

-- customers that got discount and still paid more than average 
select customer_id, purchase_amount 
from mytable
where discount_applied = "yes"
and purchase_amount >= (select avg(purchase_amount) from mytable);

-- top 5 products with highest average ratings

select item_purchased, avg(review_rating) 
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- avg purchase amounts of express and standard shipping

select shipping_type, avg(purchase_amount) 
from mytable
where shipping_type = 'Express' or shipping_type = 'Standard'
group by shipping_type;

-- comparision of subscribed and non subscribed customers
select subscription_status, count(customer_id), avg(purchase_amount), sum(purchase_amount)
from mytable
group by subscription_status;

-- products whith highest percentage of discounts applied
-- 1st try

-- select item_purchased, (select count(discount_applied) from mytable where discount_applied='Yes' )/(select count(discount_applied) from mytable)
-- from mytable
-- group by item_purchased
-  order by count(discount_applied) desc
-- limit 5;

-- 2nd try
select item_purchased,
100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;


-- subscribed customers vs non subscribed customers
select count(customer_id), subscription_status
from mytable
where previous_purchases >= 5
group by subscription_status;

select age_groups, sum(purchase_amount) 
from mytable
group by age_groups
order by sum(purchase_amount) desc;